/// Shared country + city data for dropdown fields throughout the app.
/// Add cities as the business expands.
class LocationData {
  LocationData._();

  static const List<String> countries = [
    'Bosnia and Herzegovina',
    'Croatia',
    'Serbia',
    'Slovenia',
    'Montenegro',
    'North Macedonia',
    'Austria',
    'Germany',
    'Switzerland',
    'Netherlands',
    'Belgium',
    'France',
    'Italy',
    'United Kingdom',
    'Sweden',
    'Norway',
    'Denmark',
    'United States',
    'Canada',
  ];

  /// Returns a list of major cities for the given country.
  /// Always includes "Other" at the end so the user can type a custom city.
  static List<String> citiesFor(String country) {
    final list = _cityMap[country] ?? [];
    return [...list, 'Other'];
  }

  static const Map<String, List<String>> _cityMap = {
    'Bosnia and Herzegovina': [
      'Sarajevo',
      'Mostar',
      'Banja Luka',
      'Tuzla',
      'Zenica',
      'Travnik',
      'Livno',
      'Goražde',
      'Trebinje',
      'Brčko',
      'Bijeljina',
      'Cazin',
      'Bugojno',
      'Konjic',
      'Vitez',
    ],
    'Croatia': [
      'Zagreb',
      'Split',
      'Rijeka',
      'Osijek',
      'Zadar',
      'Slavonski Brod',
      'Pula',
      'Sisak',
      'Karlovac',
      'Varaždin',
      'Šibenik',
      'Dubrovnik',
    ],
    'Serbia': [
      'Belgrade',
      'Novi Sad',
      'Niš',
      'Kragujevac',
      'Subotica',
      'Zrenjanin',
      'Pančevo',
      'Čačak',
      'Novi Pazar',
      'Šabac',
    ],
    'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Velenje'],
    'Montenegro': [
      'Podgorica',
      'Nikšić',
      'Bar',
      'Herceg Novi',
      'Bijelo Polje',
      'Budva',
    ],
    'North Macedonia': ['Skopje', 'Bitola', 'Ohrid', 'Kumanovo', 'Tetovo'],
    'Austria': [
      'Vienna',
      'Graz',
      'Linz',
      'Salzburg',
      'Innsbruck',
      'Klagenfurt',
    ],
    'Germany': [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Düsseldorf',
      'Leipzig',
      'Dortmund',
      'Essen',
      'Bremen',
      'Dresden',
      'Nuremberg',
    ],
    'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Lucerne'],
    'Netherlands': [
      'Amsterdam',
      'Rotterdam',
      'The Hague',
      'Utrecht',
      'Eindhoven',
    ],
    'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Liège', 'Bruges'],
    'France': [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Bordeaux',
      'Lille',
    ],
    'Italy': [
      'Rome',
      'Milan',
      'Naples',
      'Turin',
      'Palermo',
      'Genoa',
      'Bologna',
      'Florence',
      'Venice',
    ],
    'United Kingdom': [
      'London',
      'Birmingham',
      'Manchester',
      'Liverpool',
      'Sheffield',
      'Edinburgh',
      'Glasgow',
      'Leeds',
      'Bristol',
      'Cardiff',
    ],
    'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
    'Norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Tromsø'],
    'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
    'United States': [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'Austin',
      'Miami',
      'Seattle',
      'Denver',
      'Washington DC',
      'Boston',
    ],
    'Canada': [
      'Toronto',
      'Montreal',
      'Vancouver',
      'Calgary',
      'Ottawa',
      'Edmonton',
      'Winnipeg',
    ],
  };
}
